---
- name: Check if already installed
  ansible.builtin.stat:
    path: "{{ owntone_path_binary }}"
  register: owntone_binary_register
  tags: owntone

- name: Get installed version
  ansible.builtin.shell: |
    set -o pipefail
    {{ owntone_binary_register.stat.path }} --version | cut -f2 -d ' '
  args:
    executable: /bin/bash
  register: owntone_version_register
  changed_when: false
  when: owntone_binary_register.stat.exists
  tags: owntone

- block:
    - name: Download source
      ansible.builtin.git:
        repo: "{{ owntone_git_repo }}"
        dest: "{{ owntone_git_dest }}"
        version: "{{ owntone_version }}"

    - name: Configure build
      ansible.builtin.shell:
        cmd: >
          autoreconf -i &&
          ./configure
          --prefix=/usr
          --sysconfdir=/etc
          --localstatedir=/var
          --enable-install-user
          {% if owntone_enable_chromecast %}
          --enable-chromecast
          {% endif %}
          {% if owntone_enable_libspotify %}
          --enable-libspotify
          {% endif %}
          {% if owntone_enable_pulseaudio %}
          --with-pulseaudio
          {% endif %}
          {% if owntone_disable_spotify %}
          --disable-spotify
          {% endif %}
          {% if owntone_disable_playerwebui %}
          --disable-webinterface
          {% endif %}
          {% if owntone_disable_livewebui %}
          --without-libwebsockets
          {% endif %}
        chdir: "{{ owntone_git_dest }}"
      changed_when: true

    - name: Install
      ansible.builtin.make:
        chdir: "{{ owntone_git_dest }}"
        target: install

  when: ('owntone_reinstall' in ansible_run_tags) or not owntone_binary_register.stat.exists or (owntone_version_register.stdout | default('')) != owntone_version
  notify: restart owntone
  become: true
  tags:
    - owntone
    - owntone_reinstall
