---
- name: Install gpg
  ansible.builtin.apt:
    name: gpg
    state: present
  become: true
  tags: owntone

- name: Add mopidy key
  ansible.builtin.apt_key:
    url: https://apt.mopidy.com/mopidy.gpg
    state: present
  become: true
  tags: owntone

- name: Add mopidy repo
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  become: true
  tags: owntone
  loop:
    - deb https://apt.mopidy.com/ buster main contrib non-free
    - deb-src https://apt.mopidy.com/ buster main contrib non-free
