---
- name: Add feature packages
  ansible.builtin.set_fact:
    owntone_packages: "{{ owntone_packages + [item.package] }}"
  tags: owntone
  when: item.enable | bool
  loop:
    - package: "{{ owntone_package_chromecast }}"
      enable: "{{ owntone_enable_chromecast }}"
    - package: "{{ owntone_package_pulseaudio }}"
      enable: "{{ owntone_enable_pulseaudio }}"
    - package: "{{ owntone_package_libspotify }}"
      enable: "{{ owntone_enable_libspotify }}"

- import_tasks: libspotify.yml
  when: owntone_enable_libspotify | bool
  tags: owntone

- name: Install packages
  ansible.builtin.apt:
    name: "{{ owntone_packages }}"
    state: present
    install_recommends: false
  become: true
  tags: owntone

- import_tasks: install.yml
  tags: owntone

- name: Copy config file
  ansible.builtin.copy:
    content: "{{ owntone_config }}"
    dest: "{{ owntone_path_config }}"
    owner: owntone
    group: owntone
    mode: 0600
  become: true
  notify: restart owntone
  tags: owntone
  when: owntone_config is defined

- name: Enable service
  ansible.builtin.systemd:
    name: owntone
    enabled: true
  become: true
  tags: owntone

- name: Fix static noise on intel audio
  ansible.builtin.copy:
    content: >
      options snd-hda-intel power_save=0 power_save_controller=N
    dest: /etc/modprobe.d/alsa-base.conf
    mode: 0644
  become: true
  notify: commit alsa intel audio static fix
  tags: owntone
  when: owntone_alsa_intel_audio_static_fix | bool

- name: Unfix static noise on intel audio
  ansible.builtin.file:
    path: /etc/modprobe.d/alsa-base.conf
    state: absent
  become: true
  notify: commit alsa intel audio static fix
  tags: owntone
  when: not (owntone_alsa_intel_audio_static_fix | bool)
