---
- name: Add chromecast package
  ansible.builtin.set_fact:
    owntone_packages: "{{ owntone_packages + [owntone_package_chromecast] }}"
  tags: owntone
  when: owntone_enable_chromecast | bool

- name: Add pulseaudio package
  ansible.builtin.set_fact:
    owntone_packages: "{{ owntone_packages + [owntone_package_pulseaudio] }}"
  tags: owntone
  when: owntone_enable_pulseaudio | bool

- import_tasks: libspotify.yml
  when: owntone_enable_libspotify | bool
  tags: owntone

- name: Install owntone packages
  ansible.builtin.apt:
    name: "{{ owntone_packages }}"
    state: present
  become: true
  tags: owntone

- import_tasks: install.yml

- name: Copy owntone config file
  ansible.builtin.copy:
    content: "{{ owntone_config }}"
    dest: "{{ owntone_path_config }}"
    owner: owntone
    group: owntone
    mode: "0600"
  become: true
  notify: restart owntone
  tags: owntone
  when: owntone_config is defined

- name: Enable owntone
  ansible.builtin.systemd:
    name: owntone
    enabled: true
  become: true
  tags: owntone

- name: Fix static noise on Intel audio
  ansible.builtin.copy:
    content: >
      options snd-hda-intel power_save=0 power_save_controller=N
    dest: /etc/modprobe.d/alsa-base.conf
    mode: 0644
  become: true
  notify: commit alsa intel audio static fix
  tags: owntone
  when: owntone_alsa_intel_audio_static_fix | bool

- name: Unfix static noise on Intel audio
  ansible.builtin.file:
    path: /etc/modprobe.d/alsa-base.conf
    state: absent
  become: true
  notify: commit alsa intel audio static fix
  tags: owntone
  when: not (owntone_alsa_intel_audio_static_fix | bool)
