---
- name: Add chromecast package
  set_fact:
    owntone_packages: "{{ owntone_packages + [owntone_package_chromecast] }}"
  tags: owntone
  when: owntone_enable_chromecast | bool

- name: Add pulseaudio package
  set_fact:
    owntone_packages: "{{ owntone_packages + [owntone_package_pulseaudio] }}"
  tags: owntone
  when: owntone_enable_pulseaudio | bool

- import_tasks: libspotify.yml
  when: owntone_enable_libspotify | bool
  tags: owntone

- name: Install owntone packages
  apt:
    name: "{{ owntone_packages }}"
    state: present
  become: true
  tags: owntone

- import_tasks: install.yml

- name: Copy owntone config file
  copy:
    content: "{{ owntone_config }}"
    dest: "{{ owntone_path_config }}"
    owner: owntone
    group: owntone
    mode: "0600"
  become: true
  notify: restart owntone
  tags: owntone
  when: owntone_config is defined

- name: Enable owntone
  systemd:
    name: owntone
    enabled: true
  become: true
  tags: owntone
