---
- name: Converge
  hosts: all
  vars:
    owntone_enable_chromecast: true
    owntone_enable_libspotify: true
    owntone_enable_pulseaudio: true
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
      become: true
  tasks:
    - name: "Import itsnotgoodname.owntone"
      ansible.builtin.import_role:
        name: "itsnotgoodname.owntone"
    - name: Start dbus for avahi
      ansible.builtin.systemd:
        name: dbus
        state: started
      become: true
