---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Get installed version
      ansible.builtin.shell: |
        set -o pipefail
        {{ owntone_path_binary }} --version | cut -f2 -d ' '
      args:
        executable: /bin/bash
      register: owntone_version_register
      changed_when: false

    - name: Collect facts about system services
      ansible.builtin.service_facts:
      register: services_state

    - name: Assert
      ansible.builtin.assert:
        that:
          - services_state.ansible_facts.services["owntone.service"]["state"] == "running"
          - services_state.ansible_facts.services["owntone.service"]["status"] == "enabled"
          - owntone_version_register.stdout == owntone_version
